name = "BinaryTreeTassellation"
uuid = "a1bd8c7a-885e-482b-815a-8e3a7dae0535"
authors = ["Vittorio Erba <vittorio.erba@posteo.net> and contributors"]
version = "0.1.0"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
